// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/events": {
            "post": {
                "description": "Creates a new event and persists it to the configured database",
                "tags": [
                    "events"
                ],
                "summary": "Create a new event",
                "operationId": "CreateEvent",
                "parameters": [
                    {
                        "description": "Event data",
                        "name": "event",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/CreateEventRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/CreateEventResponse"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    }
                }
            }
        },
        "/events/batch": {
            "post": {
                "description": "Creates multiple events in a single batch operation",
                "tags": [
                    "events"
                ],
                "summary": "Create multiple events",
                "operationId": "CreateEventBatch",
                "parameters": [
                    {
                        "description": "Events data",
                        "name": "events",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/CreateEventBatchRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/CreateEventBatchResponse"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    }
                }
            }
        },
        "/events/metrics": {
            "get": {
                "description": "Retrieves aggregated metrics for events with optional grouping",
                "tags": [
                    "events"
                ],
                "summary": "Get event metrics",
                "operationId": "GetMetrics",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Event name to filter by",
                        "name": "event_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Start timestamp (RFC3339 format)",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End timestamp (RFC3339 format)",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Aggregation type: channel, daily, hourly",
                        "name": "group_by",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/GetMetricsResponse"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "AppInfoRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "CreateEventBatchRequest": {
            "type": "object",
            "required": [
                "events"
            ],
            "properties": {
                "events": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/CreateEventRequest"
                    }
                }
            }
        },
        "CreateEventBatchResponse": {
            "type": "object",
            "properties": {
                "ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "CreateEventRequest": {
            "type": "object",
            "required": [
                "channel_type",
                "name"
            ],
            "properties": {
                "app_info": {
                    "$ref": "#/definitions/AppInfoRequest"
                },
                "channel_type": {
                    "type": "string",
                    "enum": [
                        "web",
                        "mobile",
                        "desktop",
                        "tv",
                        "console",
                        "other"
                    ]
                },
                "date": {
                    "type": "string"
                },
                "device": {
                    "$ref": "#/definitions/DeviceRequest"
                },
                "event_params": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ParamRequest"
                    }
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ItemRequest"
                    }
                },
                "name": {
                    "type": "string"
                },
                "previous_timestamp": {
                    "type": "integer"
                },
                "timestamp": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "string"
                },
                "user_params": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ParamRequest"
                    }
                },
                "user_pseudo_id": {
                    "type": "string"
                }
            }
        },
        "CreateEventResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "DeviceRequest": {
            "type": "object",
            "properties": {
                "browser_name": {
                    "type": "string"
                },
                "browser_version": {
                    "type": "string"
                },
                "category": {
                    "type": "string"
                },
                "hostname": {
                    "type": "string"
                },
                "language": {
                    "type": "string"
                },
                "mobile_brand_name": {
                    "type": "string"
                },
                "mobile_model_name": {
                    "type": "string"
                },
                "operating_system": {
                    "type": "string"
                },
                "operating_system_version": {
                    "type": "string"
                }
            }
        },
        "Error": {
            "type": "object",
            "required": [
                "code",
                "message"
            ],
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "GetMetricsResponse": {
            "type": "object",
            "properties": {
                "event_name": {
                    "type": "string"
                },
                "from": {
                    "type": "string"
                },
                "grouped_metrics": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/GroupedMetricResponse"
                    }
                },
                "to": {
                    "type": "string"
                },
                "total_count": {
                    "type": "integer"
                },
                "unique_user_count": {
                    "type": "integer"
                }
            }
        },
        "GroupedMetricResponse": {
            "type": "object",
            "properties": {
                "group_key": {
                    "type": "string"
                },
                "total_count": {
                    "type": "integer"
                },
                "unique_user_count": {
                    "type": "integer"
                }
            }
        },
        "ItemRequest": {
            "type": "object",
            "properties": {
                "brand": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "list_id": {
                    "type": "string"
                },
                "list_name": {
                    "type": "string"
                },
                "location_id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "params": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ParamRequest"
                    }
                },
                "price_in_usd": {
                    "type": "number"
                },
                "promotion_id": {
                    "type": "string"
                },
                "promotion_name": {
                    "type": "string"
                },
                "quantity": {
                    "type": "integer"
                },
                "revenue_in_usd": {
                    "type": "number"
                },
                "variant": {
                    "type": "string"
                }
            }
        },
        "ParamRequest": {
            "type": "object",
            "required": [
                "key"
            ],
            "properties": {
                "boolean_value": {
                    "type": "boolean"
                },
                "key": {
                    "type": "string"
                },
                "number_value": {
                    "type": "number"
                },
                "string_value": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
